package pageUIs.orangeHRM.pim.employee;

public class QualificationsPUI {
    public static final String ADD_WORK_EXPERIENCE_BUTTON = "xpath=//h6[text()='Work Experience']/following-sibling::button";
    public static final String COMPANY_TEXTBOX = "xpath=//label[text()='Company']/parent::div/following-sibling::div/input";
    public static final String JOB_TITLE_TEXTBOX = "xpath=//label[text()='Job Title']/parent::div/following-sibling::div/input";
    public static final String START_DATE_OF_WORK_TEXTBOX = "xpath=//label[contains(text(), 'From')]/parent::div/following-sibling::div//input";
    public static final String END_DATE_OF_WORK_TEXTBOX = "xpath=//label[contains(text(), 'To')]/parent::div/following-sibling::div//input";
    public static final String ADD_EDUCATION_BUTTON = "xpath=//h6[text()='Education']/following-sibling::button";
    public static final String LEVEL_DROPDOWN_PARENT = "xpath=//label[contains(text(), 'Level')]/parent::div/following-sibling::div//i";
    public static final String LEVEL_DROPDOWN_CHILD = "xpath=//label[contains(text(), 'Level')]/parent::div/following-sibling::div//div[@class='oxd-select-option']/span";
    public static final String INSTITUTE_TEXTBOX = "xpath=//label[text()='Institute']/parent::div/following-sibling::div/input";
    public static final String MAJOR_TEXTBOX = "xpath=//label[text()='Major/Specialization']/parent::div/following-sibling::div/input";
    public static final String YEAR_TEXTBOX = "xpath=//label[contains(text(), 'Year')]/parent::div/following-sibling::div//input";
    public static final String SCORE_TEXTBOX = "xpath=//label[contains(text(), 'GPA/Score')]/parent::div/following-sibling::div//input";
    public static final String START_DATE_OF_EDUCATION_TEXTBOX = "xpath=//label[contains(text(), 'Start Date')]/parent::div/following-sibling::div//input";
    public static final String END_DATE_OF_EDUCATION_TEXTBOX = "xpath=//label[contains(text(), 'End Date')]/parent::div/following-sibling::div//input";
    public static final String ADD_SKILLS_BUTTON = "xpath=//h6[text()='Skills']/following-sibling::button";
    public static final String SKILL_DROPDOWN_PARENT = "xpath=//label[contains(text(), 'Skill')]/parent::div/following-sibling::div//i";
    public static final String SKILL_DROPDOWN_CHILD = "xpath=//label[contains(text(), 'Skill')]/parent::div/following-sibling::div//div[@class='oxd-select-option']/span";
    public static final String YEAR_OF_EXPERIENCE_TEXTBOX = "xpath=//label[contains(text(), 'Years of Experience')]/parent::div/following-sibling::div//input";
    public static final String ADD_LANGUAGES_BUTTON = "xpath=//h6[text()='Languages']/following-sibling::button";
    public static final String LANGUAGE_DROPDOWN_PARENT = "xpath=//label[contains(text(), 'Language')]/parent::div/following-sibling::div//i";
    public static final String LANGUAGE_DROPDOWN_CHILD = "xpath=//label[contains(text(), 'Language')]/parent::div/following-sibling::div//div[@class='oxd-select-option']/span";
    public static final String FLUENCY_DROPDOWN_PARENT = "xpath=//label[contains(text(), 'Fluency')]/parent::div/following-sibling::div//i";
    public static final String FLUENCY_DROPDOWN_CHILD = "xpath=//label[contains(text(), 'Fluency')]/parent::div/following-sibling::div//div[@class='oxd-select-option']/span";
    public static final String COMPETENCY_DROPDOWN_PARENT = "xpath=//label[contains(text(), 'Competency')]/parent::div/following-sibling::div//i";
    public static final String COMPETENCY_DROPDOWN_CHILD = "xpath=//label[contains(text(), 'Competency')]/parent::div/following-sibling::div//div[@class='oxd-select-option']/span";
    public static final String ADD_LICENSE_BUTTON = "xpath=//h6[text()='License']/following-sibling::button";
    public static final String LICENSE_TYPE_DROPDOWN_PARENT = "xpath=//label[contains(text(), 'License Type')]/parent::div/following-sibling::div//i";
    public static final String LICENSE_TYPE_DROPDOWN_CHILD = "xpath=//label[contains(text(), 'License Type')]/parent::div/following-sibling::div//div[@class='oxd-select-option']/span";
    public static final String LICENSE_NUMBER_TEXTBOX = "xpath=//label[text()='License Number']/parent::div/following-sibling::div/input";
    public static final String START_DATE_OF_LICENSE_TEXTBOX = "xpath=//label[contains(text(), 'Issued Date')]/parent::div/following-sibling::div//input";
    public static final String END_DATE_OF_LICENSE_TEXTBOX = "xpath=//label[contains(text(), 'Expiry Date')]/parent::div/following-sibling::div//input";
    public static final String COMPANY_NAME_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String JOB_TITLE_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String START_DATE_OF_WORK_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String END_DATE_OF_WORK_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String LEVEL_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String YEAR_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String SCORE_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String SKILL_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String LANGUAGE_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String FLUENCY_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String COMPETENCY_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String LICENSE_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String START_DATE_OF_LICENSE_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String END_DATE_OF_LICENSE_COLUMN = "xpath=//div[@class='oxd-table-body']//div[text()='%s']";
    public static final String SAVE_BUTTON_AT_QUALIFICATIONS_CONTAINER = "xpath=//button[normalize-space()='Save']";
}